<?php
/**
 * @file
 * Customizations for Rochester.
 */

/**
 * Implements hook_menu().
 */
function rochdora_menu() {
  $items = array();
  $items['islandora/object/%islandora_object/manage/collection/volume_batch'] = array(
    'title' => 'Volume Batch',
    'access callback' => 'rochdora_volume_batch_menu_access',
    'access arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rochdora_volume_batch_form', 2),
    'file' => 'includes/batch.form.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['rochdora/compound_block/%islandora_object'] = array(
    'title' => 'Compound Block Callback',
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
    'page callback' => 'rochdora_compound_block',
    'page arguments' => array(2),
    'file' => 'includes/callbacks.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implements hook_CMODEL_PID_islandora_solr_object_result_alter().
 *
 * Replaces the url for the search result to be the book's url, not the page.
 * The page is added as a fragment at the end of the book url.
 */
function rochdora_islandora_pageCModel_islandora_solr_object_result_alter(&$search_results, $query_processor) {
  // Grab the names of the appropriate solr fields from the db.
  $parent_book_field_name = variable_get('islandora_book_parent_book_solr_field', 'RELS_EXT_isMemberOf_uri_ms');
  $page_number_field_name = variable_get('islandora_paged_content_page_number_solr_field', 'RELS_EXT_isSequenceNumber_literal_ms');
  // If:
  // there's an object url AND
  // there's a solr doc AND
  // the solr doc contains the parent book AND
  // the solr doc contains the page number...
  if (isset($search_results['object_url']) &&
      isset($search_results['solr_doc']) &&
      isset($search_results['solr_doc'][$parent_book_field_name]) &&
      count($search_results['solr_doc'][$parent_book_field_name]) &&
      isset($search_results['solr_doc'][$page_number_field_name]) &&
      count($search_results['solr_doc'][$page_number_field_name])) {
    // Replace the result url with that of the parent book and add the page
    // number as a fragment.
    $book_pid = preg_replace('/info\:fedora\//', '', $search_results['solr_doc'][$parent_book_field_name][0], 1);
    $page_number = $search_results['solr_doc'][$page_number_field_name][0];

    if (islandora_object_access(ISLANDORA_VIEW_OBJECTS, islandora_object_load($book_pid))) {     
      $search_results['object_url_params'] = array('islandora_paged_content_page' => $page_number);   
    }
  }
}


/**
 * Menu access callback.
 */
function rochdora_volume_batch_menu_access($object) {
  if (!islandora_object_access(ISLANDORA_INGEST, $object)) {
    return FALSE;
  }

  $c = 'COLLECTION_POLICY';
  if (isset($object[$c]) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object[$c])) {
    $cp = new CollectionPolicy($object[$c]->content);

    return array_key_exists('islandora:bookCModel', $cp->getContentModels());
  }

  return FALSE;
}

/**
 * Implements hook_block_info().
 *
 * Prints a compound block on books.
 */
function rochdora_block_view_islandora_compound_object_compound_navigation_alter(&$data, $block) {
    $object = menu_get_object('islandora_object', 2);
  if ($object && !$data['content'] && in_array('islandora:bookCModel', $object->models)) {
    module_load_include('inc', 'islandora_compound_object', 'includes/blocks');
    module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
    $page = isset($_GET['islandora_paged_content_page']) ? $_GET['islandora_paged_content_page'] : 1;
    $pages = islandora_paged_content_get_pages($object);
    foreach ($pages as $page_array) {
      if ($page_array['page'] == $page) {
        $page_object = islandora_object_load($page_array['pid']);
        break;
      }
    }
    $data['content'] = islandora_compound_object_navigation_block($page_object);
    // Using a hidden value to populate the sidebar.
    if (!$data['content']) {
      $data['content'] = array(
        '#type' => 'hidden',
      );
    }
    drupal_add_js(drupal_get_path('module', 'rochdora') . '/js/book_page_compound_block.js');
  }
}

/**
 * Implements hook_islandora_CMODEL_derivative().
 */
function rochdora_islandora_compoundCModel_islandora_derivative() {
  $module_path = drupal_get_path('module', 'rochdora');
  return array(
    'rochdora_compound_thumbnail' => array(
      'source_dsid' => NULL,
      'destination_dsid' => 'TN',
      'function' => array('rochdora_compound_derive_thumbnail_of_parent'),
      'file' => "$module_path/includes/derivatives.inc",
    ),
  );
}

/**
 * Implements hook_islandora_derivative().
 */
function rochdora_islandora_derivative() {
  $module_path = drupal_get_path('module', 'rochdora');
  return array(
    'rochdora_compound_child_thumbnail' => array(
      'source_dsid' => 'TN',
      'destination_dsid' => 'NULL',
      'function' => array('rochdora_compound_derive_thumbnail_on_parent'),
      'file' => "$module_path/includes/derivatives.inc",
    ),
  );
}
